###############################################################################
# AWS <-> GCP private connectivity via HA VPN + BGP (no native cross-cloud
# peering exists). Builds a redundant 4-tunnel IPsec mesh between the EKS VPC and
# the GKE VPC with dynamic BGP routing — the private substrate the central
# CockroachDB (and optional cross-cloud pod traffic) rides on.
#
# Topology: GCP HA VPN gateway (2 interfaces) <-> AWS VPN gateway via 2 AWS VPN
# connections (4 tunnels total). PSKs + BGP inside addresses are generated by AWS
# and consumed by the GCP side, so ordering is handled by Terraform references.
###############################################################################

terraform {
  required_providers {
    aws    = { source = "hashicorp/aws" }
    google = { source = "hashicorp/google" }
  }
}

# ---- GCP: HA VPN gateway + Cloud Router (BGP) ----
resource "google_compute_ha_vpn_gateway" "gcp" {
  name    = "${var.name_prefix}-ha-vpn"
  region  = var.gcp_region
  network = var.gcp_network
}

resource "google_compute_router" "gcp" {
  name    = "${var.name_prefix}-cr"
  region  = var.gcp_region
  network = var.gcp_network
  bgp {
    asn            = var.gcp_router_asn
    advertise_mode = "CUSTOM"
    # advertise the GKE subnet + pod + service ranges to AWS so EKS can route to
    # GKE pods (CockroachDB node-to-node). AWS advertises its VPC CIDR by default.
    advertised_ip_ranges {
      range = var.gke_subnet_cidr
    }
    advertised_ip_ranges {
      range = var.gke_pods_cidr
    }
    advertised_ip_ranges {
      range = var.gke_services_cidr
    }
  }
}

# Allow EKS (AWS VPC CIDR) into the GKE network over the VPN.
resource "google_compute_firewall" "from_aws" {
  name          = "${var.name_prefix}-allow-aws"
  network       = var.gcp_network
  direction     = "INGRESS"
  source_ranges = [var.aws_vpc_cidr]
  allow {
    protocol = "tcp"
  }
  allow {
    protocol = "udp"
  }
  allow {
    protocol = "icmp"
  }
}

# Allow GKE (subnet + pods) into the EKS nodes over the VPN.
resource "aws_security_group_rule" "from_gke" {
  type              = "ingress"
  security_group_id = var.eks_node_security_group_id
  protocol          = "tcp"
  from_port         = 0
  to_port           = 65535
  cidr_blocks       = [var.gke_subnet_cidr, var.gke_pods_cidr]
  description       = "Cross-cloud: GKE pods/nodes -> EKS nodes (CockroachDB :26257 etc.)"
}

# ---- AWS: VPN gateway attached to the EKS VPC ----
resource "aws_vpn_gateway" "aws" {
  vpc_id          = var.aws_vpc_id
  amazon_side_asn = var.aws_amazon_side_asn
  tags            = { Name = "${var.name_prefix}-vgw" }
}

resource "aws_vpn_gateway_route_propagation" "prop" {
  count          = length(var.aws_route_table_ids)
  vpn_gateway_id = aws_vpn_gateway.aws.id
  route_table_id = var.aws_route_table_ids[count.index]
}

# AWS customer gateways = the GCP HA VPN's two interface IPs
resource "aws_customer_gateway" "gcp" {
  count      = 2
  bgp_asn    = var.gcp_router_asn
  ip_address = google_compute_ha_vpn_gateway.gcp.vpn_interfaces[count.index].ip_address
  type       = "ipsec.1"
  tags       = { Name = "${var.name_prefix}-cgw-${count.index}" }
}

# Two AWS VPN connections (2 BGP tunnels each = 4 tunnels)
resource "aws_vpn_connection" "conn" {
  count               = 2
  vpn_gateway_id      = aws_vpn_gateway.aws.id
  customer_gateway_id = aws_customer_gateway.gcp[count.index].id
  type                = "ipsec.1"
  static_routes_only  = false # dynamic (BGP)
  tags                = { Name = "${var.name_prefix}-vpn-${count.index}" }
}

# GCP-side representation of AWS's 4 tunnel outside IPs
resource "google_compute_external_vpn_gateway" "aws" {
  name            = "${var.name_prefix}-aws"
  redundancy_type = "FOUR_IPS_REDUNDANCY"
  interface {
    id         = 0
    ip_address = aws_vpn_connection.conn[0].tunnel1_address
  }
  interface {
    id         = 1
    ip_address = aws_vpn_connection.conn[0].tunnel2_address
  }
  interface {
    id         = 2
    ip_address = aws_vpn_connection.conn[1].tunnel1_address
  }
  interface {
    id         = 3
    ip_address = aws_vpn_connection.conn[1].tunnel2_address
  }
}

locals {
  # map each of the 4 GCP tunnels to the matching AWS tunnel's PSK + BGP inside IPs
  tuns = [
    { gw_if = 0, ext_if = 0, psk = aws_vpn_connection.conn[0].tunnel1_preshared_key, cgw = aws_vpn_connection.conn[0].tunnel1_cgw_inside_address, vgw = aws_vpn_connection.conn[0].tunnel1_vgw_inside_address },
    { gw_if = 0, ext_if = 1, psk = aws_vpn_connection.conn[0].tunnel2_preshared_key, cgw = aws_vpn_connection.conn[0].tunnel2_cgw_inside_address, vgw = aws_vpn_connection.conn[0].tunnel2_vgw_inside_address },
    { gw_if = 1, ext_if = 2, psk = aws_vpn_connection.conn[1].tunnel1_preshared_key, cgw = aws_vpn_connection.conn[1].tunnel1_cgw_inside_address, vgw = aws_vpn_connection.conn[1].tunnel1_vgw_inside_address },
    { gw_if = 1, ext_if = 3, psk = aws_vpn_connection.conn[1].tunnel2_preshared_key, cgw = aws_vpn_connection.conn[1].tunnel2_cgw_inside_address, vgw = aws_vpn_connection.conn[1].tunnel2_vgw_inside_address },
  ]
}

resource "google_compute_vpn_tunnel" "t" {
  count                           = 4
  name                            = "${var.name_prefix}-tun-${count.index}"
  region                          = var.gcp_region
  vpn_gateway                     = google_compute_ha_vpn_gateway.gcp.id
  vpn_gateway_interface           = local.tuns[count.index].gw_if
  peer_external_gateway           = google_compute_external_vpn_gateway.aws.id
  peer_external_gateway_interface = local.tuns[count.index].ext_if
  shared_secret                   = local.tuns[count.index].psk
  router                          = google_compute_router.gcp.id
  ike_version                     = 2
}

resource "google_compute_router_interface" "ri" {
  count      = 4
  name       = "${var.name_prefix}-ri-${count.index}"
  router     = google_compute_router.gcp.name
  region     = var.gcp_region
  ip_range   = "${local.tuns[count.index].cgw}/30"
  vpn_tunnel = google_compute_vpn_tunnel.t[count.index].name
}

resource "google_compute_router_peer" "rp" {
  count           = 4
  name            = "${var.name_prefix}-rp-${count.index}"
  router          = google_compute_router.gcp.name
  region          = var.gcp_region
  peer_ip_address = local.tuns[count.index].vgw
  peer_asn        = var.aws_amazon_side_asn
  interface       = google_compute_router_interface.ri[count.index].name
}
